export const proofVaultRegistryAbi = [
  "event ProjectRegistered(bytes32 indexed projectId,string name,string slug,bytes32 websiteHash,bytes32 metadataHash,address indexed owner,uint256 createdAt)",
  "event ProofRequestCreated(uint256 indexed requestId,bytes32 indexed projectId,bytes32 thresholdCommitment,bytes32 selectedAssetsHash,string selectedAssets,bytes32 metadataHash,address indexed createdBy,uint256 createdAt)",
  "event ProofResultSubmitted(uint256 indexed resultId,uint256 indexed requestId,bytes32 indexed projectId,bytes32 proofHash,uint8 outcome,bool thresholdMet,bytes32 resultMetadataHash,address submittedBy,uint256 submittedAt)",
  "event WorkerSignerUpdated(address indexed signer,bool authorized,uint256 updatedAt)",
  "function registerProject(string name,string slug,bytes32 websiteHash,bytes32 metadataHash) returns (bytes32 projectId)",
  "function projectExists(string slug) view returns (bool)",
  "function getProjectBySlug(string slug) view returns (tuple(string name,string slug,bytes32 websiteHash,bytes32 metadataHash,address owner,bool exists,uint256 createdAt,uint256 updatedAt))",
  "function createProofRequest(string slug,bytes32 thresholdCommitment,string selectedAssets,bytes32 selectedAssetsHash,bytes32 metadataHash) returns (uint256 requestId)",
  "function getProofRequest(uint256 requestId) view returns (tuple(uint256 id,bytes32 projectId,bytes32 thresholdCommitment,bytes32 selectedAssetsHash,string selectedAssets,bytes32 metadataHash,address createdBy,uint256 createdAt,uint8 status,bool exists))",
  "function getProjectProofRequestIds(string slug) view returns (uint256[])",
  "function getProofRequestCount() view returns (uint256)",
  "function submitProofResult(uint256 requestId,bytes32 proofHash,uint8 outcome,bytes32 resultMetadataHash,uint256 workerSignedAt,bytes signature) returns (uint256 resultId)",
  "function getProofResult(uint256 resultId) view returns (tuple(uint256 id,uint256 requestId,bytes32 projectId,bytes32 proofHash,uint8 outcome,bool thresholdMet,bytes32 resultMetadataHash,address submittedBy,address relayedBy,uint256 workerSignedAt,uint256 submittedAt,bool exists))",
  "function getProofResultByRequestId(uint256 requestId) view returns (tuple(uint256 id,uint256 requestId,bytes32 projectId,bytes32 proofHash,uint8 outcome,bool thresholdMet,bytes32 resultMetadataHash,address submittedBy,address relayedBy,uint256 workerSignedAt,uint256 submittedAt,bool exists))",
  "function getProofResultCount() view returns (uint256)",
  "function getLatestProofResultBySlug(string slug) view returns (tuple(uint256 id,uint256 requestId,bytes32 projectId,bytes32 proofHash,uint8 outcome,bool thresholdMet,bytes32 resultMetadataHash,address submittedBy,address relayedBy,uint256 workerSignedAt,uint256 submittedAt,bool exists))",
  "function getProjectProofResultIds(string slug) view returns (uint256[])",
  "function getProjectProofResultCount(string slug) view returns (uint256)",
  "function getProjectProofResultIdAt(string slug,uint256 index) view returns (uint256)",
] as const;
